name: BuildFlow

on:
  pull_request:
    branches-ignore: [master]
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
            dotnet-version: 6.0.x

      - name: 'Checkout repo' 
        uses: actions/checkout@v2

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Test bot
        run: dotnet test
          
  build:
    needs: test
    strategy:
      matrix:
        server: [TRAVIAN_OFFICIAL, TRAVIAN_OFFICIAL_HEROUI, TTWARS]
        include:
            - server: TRAVIAN_OFFICIAL
              name: Travian Official 
            - server: TRAVIAN_OFFICIAL_HEROUI
              name: Travian Official - New hero UI
            - server: TTWARS
              name: TTWars 
    runs-on: windows-2019
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
            dotnet-version: 6.0.x
      
      - name: 'Checkout repo' 
        uses: actions/checkout@v2

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Build Bot
        run: dotnet publish WPFUI -c Release --self-contained true -p:PublishSingleFile=true -r win-x86 -p:Server=${{ matrix.server }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TBS-Build-${{ matrix.server }}-${{ github.sha }}
          path: WPFUI\bin\Release\net6.0-windows\win-x86\publish\
          if-no-files-found: error
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:        
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: TBS
      
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: TBS