name: ReleaseFlow

on:
  workflow_dispatch:
    inputs: 
      version:
        required: true

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        server: [TRAVIAN_OFFICIAL, TRAVIAN_OFFICIAL_HEROUI, TTWARS]
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
            dotnet-version: 6.0.x
      
      - name: 'Checkout repo' 
        uses: actions/checkout@v2

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Build Bot
        run: dotnet publish WPFUI -c Release --self-contained true -p:PublishSingleFile=true -r win-x86 -p:Server=${{ matrix.server }} -p:AssemblyVersion=${{github.event.inputs.version}}.0

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TBS-${{ matrix.server }}
          path: WPFUI\bin\Release\net6.0-windows\win-x86\publish\
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:        
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: TBS
      
      - name: Archive release
        run: |
          cd TBS; zip -r "TBS-${{needs.version.outputs.version}}-TravianOfficial-OldHeroUI.zip" TBS-TRAVIAN_OFFICIAL; cd ..
          cd TBS; zip -r "TBS-${{needs.version.outputs.version}}-TravianOfficial-NewHeroUI.zip" TBS-TRAVIAN_OFFICIAL_HEROUI; cd ..
          cd TBS; zip -r "TBS-${{needs.version.outputs.version}}-TTWars.zip" TBS-TTWARS; cd ..
            
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: TBS-${{github.event.inputs.version}}
          tag: ${{github.event.inputs.version}}
          commit: premium          
          artifacts: "TBS/TBS-${{github.event.inputs.version}}-TravianOfficial-OldHeroUI.zip, TBS/TBS-${{github.event.inputs.version}}-TravianOfficial-NewHeroUI.zip, TBS/TBS-${{github.event.inputs.version}}-TTWars.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Please join our Discord server for more information: [https://discord.gg/mBa4f2K](https://discord.gg/mBa4f2K)

  Discord:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Ping @everyone
        run: |
          curl --header "Content-Type: application/json" --data "{\"content\": \"@everyone\"}" "${{ secrets.DISCORD_BOT }}"
      - name: Send to discord server
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_BOT }}
          title: New release
          nodetail: true
          description: |
              Version `TBS-${{github.event.inputs.version}}`
              Click [here](https://github.com/Erol444/TravianBotSharp/releases/tag/${{github.event.inputs.version}}) to download!
  Clear:
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        server: [TRAVIAN_OFFICIAL, TRAVIAN_OFFICIAL_HEROUI, TTWARS]
    steps:
      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: TBS-${{ matrix.server }}
